### ISSUE TITLE
Do not automatically set as default editor

### ISSUE THREAD

**Issue by mbrodala** [dhoppe/puppet-vim#1]
Please add a parameter `$default_editor` (boolean, `false` by default) to trigger execution of `update-alternatives`.

ATM VIM is set as system-wide default editor as soon as a configuration file path is specified. (Which actually does not make any sense.)

**Comment by dhoppe** [comment]
I have a different opinion. Why should I install / configure VIM and use Nano as default editor?

**Comment by mbrodala** [comment]
Well, to preinstall and preconfigure VIM by default but leave the editor choice to the actual user. :-)

**Comment by dhoppe** [comment]
Done.

**Comment by mbrodala** [comment]
Thanks for adding this with 2f37462.
